services:
  neo4j:
    image: neo4j:enterprise
    volumes:
      - ${HOME}/.gds_license:/licenses/.gds_license
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=none
      - NEO4J_PLUGINS=["graph-data-science"]
      - NEO4J_dbms_security_procedures_allowlist=gds.*
      - NEO4J_dbms_security_procedures_unrestricted=gds.*
      - NEO4J_gds_enterprise_license__file=/licenses/.gds_license
      - NEO4J_gds_arrow_enabled=true
      - NEO4J_gds_export_location=/tmp/gds_graphs
      - NEO4J_gds_model_store__location=/tmp/gds_models

      # should only be used for testing
      - NEO4J_gds_arrow_advertised__listen__address=0.0.0.0:8491
      - NEO4J_gds_arrow_listen__address=0.0.0.0:8491

      - NEO4J_server_metrics_prometheus_enabled=true
      - NEO4J_server_metrics_prometheus_endpoint=0.0.0.0:2004
      - NEO4J_server_metrics_filter=*
      - NEO4J_server_metrics_enabled=true
    ports:
      - "7474:7474"
      - "7687:7687"
      - "8491:8491"
      - "2004:2004"
    restart: always
